"use strict";
console.log("hy kumail");
var userName = "kumail kazmi";
console.log(userName);
var numb = 5;
var num1 = 8;
var result = (numb * num1);
console.log(result);
var num2 = 2;
var num3 = 4;
var result = (numb + num1 / num3);
console.log(result * num2);
var $1 = 10;
var $2 = 20;
var result = $1 * $2;
console.log(result);
